# Generated by Django 4.2 on 2026-04-13 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='garment_type',
            field=models.CharField(blank=True, choices=[('full_set', 'Full Set'), ('jacket', 'Jacket'), ('trousers', 'Trousers'), ('accessory', 'Accessory')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sport',
            field=models.CharField(blank=True, choices=[('ski', 'Ski'), ('snowboard', 'Snowboard')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.product')),
            ],
            options={
                'unique_together': {('product', 'size')},
            },
        ),
    ]
