# Generated by Django 4.2 on 2026-04-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_color_product_garment_type_product_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='garment_type',
            field=models.CharField(blank=True, choices=[('full_set', 'Full Set'), ('ski_suit', 'Ski Suit'), ('jacket', 'Jacket'), ('trousers', 'Trousers'), ('accessory', 'Accessory')], max_length=20, null=True),
        ),
    ]
